<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: julie
 * Date: Thu, 02 Aug 2018 13:11:06 +0200
 */

$conf['title'] = 'Lepoles FabLab';
$conf['start'] = 'Home';
$conf['lang'] = 'fr';
$conf['template'] = 'LotarProject-dokuwiki-template-bootstrap3-119aa21';
$conf['license'] = 'gnufdl';
$conf['basedir'] = '/dokuwiki/';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['tpl']['bootstrap3'] = '1';

// end auto-generated content
